---
- name: 'Install cnitool'
  shell: GOBIN=/usr/sbin go install github.com/containernetworking/cni/cnitool@latest

- name: 'Download the CNI plugins archive to a local folder'
  become: false
  ansible.builtin.get_url:
    url: '{{ cni_plugins_download_url }}/{{ cni_plugins_archive_name }}'
    dest: '{{ cni_plugins_download_path }}/{{ cni_plugins_archive_name }}'
    checksum: 'sha256:{{ cni_plugins_checksum_url }}'
    mode: 0644
  delegate_to: localhost

- name: 'Unarchive the CNI plugins binaries on a target host'
  become: true
  ansible.builtin.unarchive:
    src: '{{ cni_plugins_download_path }}/{{ cni_plugins_archive_name }}'
    dest: '{{ cni_plugins_install_path }}'
    owner: 'root'
    group: 'root'
    mode: 0755
    exclude:
      - 'LICENSE'
      - 'README.md'
  when: not ansible_check_mode
