---
- name: 'Prepare for installing CNI plugins'
  become: true
  block:
    - name: 'Update the APT package cache'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      check_mode: false
      when: ansible_os_family == 'Debian'

    - name: 'Ensure the dependencies are installed'
      ansible.builtin.package:
        name: 'tar'
        state: 'present'

- name: 'Check if CNI plugins is installed'
  ansible.builtin.stat:
    path: '{{ cni_plugins_install_path }}/{{ cni_plugins_version }}'
  register: __cni_plugins_is_installed
